Interprefy/Interprefy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('startup.urls'))
]

Interprefy/startup/urls.py
from django.urls import path, include
from .views import (
    client_registration,
    ajax_send_pin,
    detail_client,
    intermediary_registration,
    detail_intermediary,
    top_intermediares,
    add_products_intermediary,
    loginpage,
    main,
    ListUser,
    ListProducts,
)
from django.conf import settings
from django.conf.urls.static import static



app_name = 'interprefy'

urlpatterns = [
    path('Interprefy', main, name='Interprefy'),



    path('client/registration/', client_registration, name='client_registration'),
    path('client/<slug:slug>/', detail_client, name='client_detail'),
    path('ajax_send_pin', ajax_send_pin, name='ajax_send_pin'),
    path('intermediary/registration/',intermediary_registration, name='intermediary_registration'),
    path('intermediary/<slug:slug>/', detail_intermediary, name='detail_intermediary'),
    path('intermediary/<slug:slug>/add-products', add_products_intermediary, name='add_product'),
    path('top', top_intermediares, name='top'),
    path('accounts/login/', loginpage, name='login'),

    path('api/users/', ListUser.as_view(), name='api_users'),
    path('api/products/', ListProducts.as_view(), name='api_products'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Interprefy/startup/forms.py
from typing import Any
from django import forms
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import UserCreationForm
from django.utils.text import slugify
import re
from .models import (
    CUser,
    Products
    
)


# def validate_phone_number(phonenumber):
#     if re.search(r'^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}$',phonenumber) == None:
#         raise ValidationError(
#             _("неверный формат номера телефона")
#         )

# def validate_fullname(fullname:str):
#     if len(fullname.split()) != 3:
#         raise ValidationError(
#             _("%(value)s ")# <================================
#         )
    # И если есть другие знаки кроме букв

# def validName(name):
#     if Intermediares.objects.filter(Name=name).exists():
#         return ValidationError(_("name already exists"))

class IntermediaresForm(forms.ModelForm):
    # Name = forms.CharField(max_length=50, validators=[validName])
    Email = forms.EmailField(widget=forms.EmailInput(attrs={"type":"email", 'class':'form-control', 'placeholder':'example@example.com'}))
    Description = forms.CharField(widget=forms.Textarea(attrs={"rows":"5",'class':'form-control'}))
    class Meta:
        model = CUser
        fields = ('username', 'Email', 'Description')



class ClientForm(UserCreationForm):
    TelephoneNumber = forms.CharField(max_length=15,required=True,widget=forms.TextInput(attrs={'type': 'tel', 
                                                                                                'class':"form-control", 
                                                                                                "placeholder":"+7 (987)654-32-10",
                                                                                                }))
    FullName = forms.CharField(max_length=100, required=True,widget=forms.TextInput(attrs={'class':"form-control", 
                                                                                           "placeholder":"Имя Фамилия Отчество", 
                                                                                           "id":"FullName",
                                                                                           "pattern": "",
                                                                                           }))
    # pin = forms.IntegerField(required=True,min_value=10**5, max_value=10**6)
    class Meta:
        model = CUser
        fields = 'username', 'FullName', 'TelephoneNumber', "password1", "password2"
    


    def __init__(self, *args, **kwargs):
        # pattern для FullName и для TelephoneNumber
        
        super(ClientForm, self).__init__(*args, **kwargs)    
        self.fields['TelephoneNumber'].widget.attrs['id'] = 'TelephoneNumber'
        self.fields['TelephoneNumber'].widget.attrs['pattern'] = r'^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}$'
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'User Name'
        self.fields['username'].label = ''
        self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'   
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password1'].label = ''
        self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'
        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
        self.fields['password2'].label = ''
        self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'	


class AddProductForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = ('Name', 'Price', 'UnitsInStock', 'ImageProducts')
    def __init__(self, *args, **kwargs):
        super(AddProductForm, self).__init__(*args, **kwargs)
        self.fields['ImageProducts'].required = False


# class ReviewsForm(forms.ModelForm):
#     # Подумать над прикреплением картинки
#     class Meta:
#         model = Reviews
#         fields = ('Review','Image')

Interprefy/startup/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import permission_required, login_required
from django.urls import reverse
from django.http import HttpRequest, HttpResponse
# from .tasks import sms_send, _verify_pin
from django.views.decorators.http import require_GET
from django.contrib import messages
from django.core.cache import cache
from django.contrib.auth import get_user_model
import random
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions
from .serializers import (CUserSerializer, 
                          ProductsSerializer,
                          CategorySerializer,
                          PostsSerializer,
                          )
from django.conf import settings# SMSAERO_EMAIL, SMSAERO_API_KEY
from django.db.models import Subquery
from smsaero import SmsAero
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from .forms import (ClientForm,
                    IntermediaresForm,
                    AddProductForm,
                    )
from .models import (CUser, 
                     Posts,
                     Products,
                     Categories,
                     )
User = get_user_model()


def _verify_pin(mobile_number, pin):
    """ Verify a PIN is correct """
    return pin == cache.get(mobile_number)

def _get_pin(length=6):
    """ Return a numeric PIN with length digits """
    return random.sample(range(10**(length-1), 10**length), 1)[0]


def main(request:HttpRequest):
    '''
        дефолтный all() с сортировкой по коментариям оценкам
    '''
    # context = {
    #     'top_intermediares': CUser.objects.filter().all().order_by()
    # }
    print(CUser.objects.all())
    return render(request, 'startup/main.html', {})



# @require_GET
# def main_view(request: HttpRequest) -> HttpResponse:
#     # context = {
#     #     'subscriptions': Subscription.objects.filter(Subscribe_client_id=id).select_related(Clients).select_related(Intermediares),
#     #     'posts': Intermediares.objects.filter(Subscribe_intermediary_id=Subscription.objects.filter(Subscribe_client_id=id).get('Subscribe_intermediary_id')),
#     #     'posts':Intermediares.objects.raw(f'''SELECT text_post, Intermediares.Name FROM Posts
#     #                                         INNER JOIN Intermediares ON Posts.posts_intermediary_id = Intermediares.id 
#     #                                         INNER JOIN Subscription  ON Subscription.Subscribe_intermediary_id = Intermediares.id
#     #                                         INNER JOIN Clients ON Subscription.Subscribe_client_id = Clients.id
#     #                                         WHERE Subscribe_client_id = {id}'''),
#     # }
#     return render(request, "startup/main.html", {})

@csrf_exempt
def ajax_send_pin(request: HttpRequest):
    """ Sends SMS PIN to the specified number """
    mobile_number = request.POST.get('mobile_number', "")
    if not mobile_number:
        return HttpResponse("No mobile number", mimetype='text/plain', status=403)

    pin = _get_pin()

    # store the PIN in the cache for later verification.
    cache.set(mobile_number, pin, 5*60) 

    api = SmsAero(settings.SMSAERO_EMAIL, settings.SMSAERO_API_KEY)
    res = api.send(mobile_number, f"{pin}")
    return HttpResponse("Message sent", status=200)


def client_registration(request: HttpRequest):
    if request.method == "POST":
        form = ClientForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.first_name= str(request.POST.get('FullName')).split()[0]
            user.last_name= str(request.POST.get('FullName')).split()[1]
            user.MiddleName=str(request.POST.get('FullName')).split()[2]
            user.save()
            pin = int(request.POST.get("pin", 0))
            telephone_number = request.POST.get("mobile_number", "")
            if _verify_pin(telephone_number, pin):
                form.save()
                username = form.cleaned_data["username"]
                password = form.cleaned_data["password1"]
                user = authenticate(username=username, password=password)
                login(request, user=user)
                return redirect('interprefy:client_detail', slug=user.username)
            else:
                cache.delete(telephone_number)
                messages.error(request, "Invalid PIN")
        else: messages.error(request, form.errors)
    else:
        context = {
            "form": ClientForm()
        }
        return render(request, "startup/client_reg.html", context)

@require_GET
def detail_client(request:HttpRequest, slug):
    context = {
        'users': CUser.objects.get(UserSlug=slug)
    }
    return render(request, 'startup/detail_client.html', context)

def intermediary_registration(request:HttpRequest):
    if request.method == "POST":
        form = IntermediaresForm(request.POST or None)
        if form.is_valid():
            intermediary = form.save(commit=False)
            intermediary.is_intermediary = True
            intermediary.user_permissions.set(['add_posts', 'change_posts', 'delete_posts', 'view_posts',
                                               'add_products', 'change_products', 'delete_products', 'view_products',
                                               ])
            intermediary.save()
            return redirect('Interprefery:detail_intermediary', slug=intermediary.username)
        else:
            messages.error(request, form.errors)
            return render(request, 'startup/intermediary_reg.html', {'form':IntermediaresForm(request.POST)})#<================
    else:
        context = {
            "form": IntermediaresForm()
        }
        return render(request, 'startup/intermediary_reg.html', context)
    
# @login_required
# @permission_required(perm=['add_post', 'change_post', 'delete_post'])

def detail_intermediary(request:HttpRequest, slug):
    '''
        Отображает все товары, магазины, страны откуда/в поставки/доставка
        Информация о посреднике
    '''
    # a = CUser.objects.raw(f'''SELECT id FROM CUser WHERE UserSlug={slug}''')
    intermediary_id = CUser.objects.filter(UserSlug=slug).only("id")
    context = {
        'intermediaries': CUser.objects.get(UserSlug=slug),
        'products': Products.objects.filter(IntermediaryID=Subquery(intermediary_id))
        # 'products': Products.objects.select_related(Categories).select_related(CUser).filter(UserSlug=slug).get(id)
    }
    return render(request, 'startup/detail_intermediary.html', context)

def top_intermediares(request:HttpRequest):
    context = {
        'intermediares': CUser.objects.filter(is_intermediary=True).all()
    }
    return render(request, 'startup/top_intermediary.html', context)

@login_required
def add_products_intermediary(request:HttpRequest, slug):
    if request.method == "POST":
        form = AddProductForm(request.POST, request.FILES)
        if form.is_valid():
            messages.info(request, 'created')
            product = form.save(commit=False)
            product.IntermediaryID = CUser.objects.get(UserSlug=slug)
            product.save()
            return redirect('interprefy:add_product')
        else:
            messages.info(request, form.errors)
    else:
        context = {
            'form': AddProductForm()
        }
        return render(request, 'startup/add_products_intermediary.html', context)
    
def loginpage(request:HttpRequest):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user=user)
            return render(request, 'startup/login.html', {})
    else:
        return render(request, 'startup/login.html', {})
    return render(request, 'startup/login.html', {})

class ListUser(APIView):
    # authentication_classes = []
    # permission_classes = []
    def get(self, request):
        queryset = CUser.objects.all()
        users = CUserSerializer(
            instance=queryset,
            many=True
        )
        return Response(users.data)
    
class ListProducts(APIView):
    def get(self, request):
        queryset = Products.objects.all()
        products = ProductsSerializer(
            instance=queryset,
            many=True
        )
        return Response(products.data)
    
class ListCategories(APIView):
    def get(self, request):
        queryset = Categories.objects.all()
        categories = CategorySerializer(
            instance=queryset,
            many = True
        )
        return Response(categories.data)
    
class ListPosts(APIView):
    def get(self, request):
        queryset = Posts.objects.all()
        posts = PostsSerializer(
            instance=queryset,
            many=True
        )
        return Response(posts.data)

Interprefy/startup/templates/startup/add_products_intermediary.html
{% extends 'startup/base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Submit</button>
    </form>
{% endblock %}

Interprefy/startup/templates/startup/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>
        {% block title%}
        {% endblock %}
    </title>
</head>
<body>
    <div class="container">
        {%if messages%}
        {% for message in messages%}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {%endfor%}
        {%endif%}
        {%block content%}
        {%endblock%}
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
</body>
</html>

Interprefy/startup/templates/startup/client_reg.html
{% extends 'startup/base.html' %}
{% block title %}
    Регистрация
{% endblock %}


{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    
    function send_pin() {
    $.ajax({
                url: "{% url 'interprefy:ajax_send_pin' %}",
                type: "POST",
                data: { mobile_number:  $("#TelephoneNumber").val() },
            })
            .done(function(data) {
                alert("PIN sent via SMS!");
                setTimeout(() => {
                    btn.attr("disabled", false)
                },
                60 * 1000
                )
                btn.attr("disabled", true)
            })
            .fail(function(jqXHR, textStatus, errorThrown) {
                alert(errorThrown + ' : ' + jqXHR.responseText);
            });
}
</script>
    <form method="post">
        {%csrf_token%}
        {{form}}
        <input type="tel" id="mobile_number" name="mobile_number" placeholder="79876543210" required>
        <!-- <button class="btn" type="button" onClick="send_pin()">Отправить код</button>-->
        <button class="btn btn-success" type="submit">Submit</button>
    </form>
    
{% endblock %}

Interprefy/startup/templates/startup/detail_client.html
{% extends 'startup/base.html' %}

{% block title %}
{% endblock %}

{% block content %}
    {{users}}
{% endblock %}

Interprefy/startup/templates/startup/detail_intermediary.html
{% extends 'startup/base.html' %}
{% block title %}
{% endblock %}

{% block content %}
{% include 'test_startapp/navbar.html' %}
    {% if products %}
    {% for product in products %}
        <div class="card-group">
            <div class="card">
            {% if product.ImageProducts %}
                <img src="{{product.ImageProducts.url}}" class="card-img-top" alt="..." height="100px" width="100px">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title">{{product.Name}}</h5>
                <p class="card-text">{{product.Price}}</p>
                <p class="card-text"><small class="text-body-secondary">{{product.UnitsInStock}}</small></p>
            </div>
            </div>
        </div> 
    {% endfor %} 
    {% else %} -
    {% endif %}
{% endblock %}

Interprefy/startup/templates/startup/footer.html
<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
      <!-- Left -->
      <div class="me-5 d-none d-lg-block">
        <span>Get connected with us on social networks:</span>
      </div>
      <!-- Left -->
  
      <!-- Right -->
      <div>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-google"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-linkedin"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-github"></i>
        </a>
      </div>
      <!-- Right -->
    </section>
    <!-- Section: Social media -->
  
    <!-- Section: Links  -->
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold mb-4">
              <i class="fas fa-gem me-3"></i>Company name
            </h6>
            <p>
              Here you can use rows and columns to organize your footer content. Lorem ipsum
              dolor sit amet, consectetur adipisicing elit.
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Products
            </h6>
            <p>
              <a href="#!" class="text-reset">Angular</a>
            </p>
            <p>
              <a href="#!" class="text-reset">React</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Vue</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Laravel</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Useful links
            </h6>
            <p>
              <a href="#!" class="text-reset">Pricing</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Settings</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Orders</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Help</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
            <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
            <p>
              <i class="fas fa-envelope me-3"></i>
              info@example.com
            </p>
            <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
            <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->
  
    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
      <p id="current_date_time_block"></p> Copyright:
      <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
  <script language="javascript" type="text/javascript">
    function date_time()
    {
        var current_datetime = new Date();
        var year = current_datetime.getFullYear();
        return '© ' + year;
    }
    document.getElementById('current_date_time_block').innerHTML = date_time();
</script>

  
  

Interprefy/startup/templates/startup/intermediares_posts.html
{% extends 'startup/base.html' %}
{% block title %}
    {{ ... }}
{% endblock %}

{% block content %}
    
{% endblock %}

Interprefy/startup/templates/startup/intermediary_reg.html
{% extends 'startup/base.html' %}
{% block title %}
    
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{form}}
        <!-- Name:
        <input id="Name" name= 'Name' type="text" class='form-control'>
        Email:
        <input id="Email" name= 'Email' type="email" class='form-control' placeholder='example@example.com'>
        <input id="Description" name='Description' type="text" rows="5" class='form-control' > -->
        <button class="btn btn-success" type="submit">Submit</button>
    </form>
{% endblock %}

Interprefy/startup/templates/startup/login.html
{% extends 'startup/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <input type="text" name="username">
        <input type="password" name="password">
        <button type="submit">Submit</button>
    </form>
{% endblock %}

Interprefy/startup/templates/startup/main.html
{% extends 'startup/base.html' %}

{% block content %}

{% load static %}
{% include 'startup/navbar.html' %}
<div id="carouselExampleCaptions" class="carousel slide">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'img/slide1.jpg'%}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>Example1</h5>
          <p>Some representative placeholder content for the first slide.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static 'img/slide2.jpg'%}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>Example2</h5>
          <p>Some representative placeholder content for the second slide.</p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
<div>
  <h1>Top intermediares</h1>
  <div>
      {% for top in top_intermediares %}
        <div class="card" style="width: 18rem;">
          <img src="{{top.ImageIntermediares.name}}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">{{top.username}}</h5>
            <p class="card-text">{{top.Description}}</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      {% endfor %}
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <h6 class="card-subtitle mb-2 text-body-secondary">Card subtitle</h6>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="card-link">Card link</a>
          <a href="#" class="card-link">Another link</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% include 'startup/footer.html' %}
{% endblock %}

Interprefy/startup/templates/startup/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Interprefy</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% if request.user.is_authenticated %}
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
          </ul>
        {% endif %}
        {% if not request.user.is_authenticated %}
          <div class="d-flex">
              <button type="button" class="btn btn-dark">Регистрация</button>
              <button type="button" class="btn btn-dark">Вход</button>
          </div>
        {% endif %}
      </div>
    </div>
  </nav>

Interprefy/startup/templates/startup/pin_verif.html
{% extends 'startup/base.html %}

{% block content %}

{% endblock %}

Interprefy/startup/templates/startup/top_intermediary.html
{% extends 'startup/base.html' %}

{% block title %}
{% endblock %}

{% block content %}
    {% for intermediary in intermediares %}
        <p>{{ intermediary.username }} {{ intermediary.Rating }}</p>
    {% endfor %}
{% endblock %}